"""Stable failure codes for remaining Wave-1 scientific diagnostics."""

from typing import Literal

Wave1FailureCode = Literal[
    "DID_PRETREND_EXCEEDED",
    "IV_WEAK_INSTRUMENT",
    "RDD_SUPPORT_INSUFFICIENT",
    "RCT_ATTRITION_EXCEEDED",
    "RCT_BALANCE_EXCEEDED",
    "RCT_ASSIGNMENT_LEAKAGE",
    "SCM_PREFIT_EXCEEDED",
    "SCM_SENSITIVITY_EXCEEDED",
    "MEASUREMENT_UNIT_MISMATCH",
    "MEASUREMENT_MISSINGNESS_EXCEEDED",
    "MEASUREMENT_RANGE_INVALID",
    "MEASUREMENT_DETECTION_FLAG_INVALID",
    "META_INFLUENCE_EXCEEDED",
]
